#BNF+IAT 1.0 UTF-8;
!grammar kqw;
!slot <contact>;
!slot <callPre>;
!slot <callPhone>;
!slot <callTo>;
!slot <go>;
!slot <position>;
!slot <fire>;
!slot <move>;


!start <callStart>;
<callStart>:
<fire>|
<go><position>;

<go>:去|到;
<position>:柜员机|窗口|柜台|大厅;

<fire>:语音;



